version: '2'

services:

  web:
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres
    entrypoint: ./launch.sh

  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_PASSWORD=averytest
      - POSTGRES_USER=hacktobacillus
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRESDB=hacktobacillus
